[theme]
base = "light"
primaryColor = "#171717"
backgroundColor = "#fbfbfa"
secondaryBackgroundColor = "#f4f4f0"
textColor = "#171717"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
